 Inheritance is a process in which one object acquires all the properties and behaviors of its parent object automatically.
 In such way, you can reuse, extend or modify the attributes and behaviors which are defined in other class.
 
 base class is an existing class from which the other classes are derived and inherit the methods and properties
 derived class --> the class that inherits the members of base class

 
 Types:
 
    Single inheritance --> derived class is inherited from the only one base class.
    							A --> B
    Multiple inheritance -->  class that inherits the attributes from two or more classes.
    							A1	A2	A3
    							\___|___/	
    								B
    
    Hierarchical inheritance --> deriving more than one class from a single base class
    							____A____
    							|	|	|
    							B1	B2	B3
    Multilevel inheritance --> deriving a class from another derived class
    							A --> B --> C
    Hybrid inheritance -->  combination of more than one type of inheritance.
    								  / \
    								 /_A_\
    								/     \
    								B     C   --> //Dimond problem
    								\__ __/
    								 \ D /
									  \ /




	
